### PR TITLE
Handle case sensitive file systems when using nocase option.

### PR DESCRIPTION
**Pull request by doowb**
This PR is based on this [discussion](https://github.com/jonschlinkert/fs-exists-sync/pull/1) and resolves [this issue in liftoff](https://github.com/js-cli/js-liftoff/issues/72).

This uses [detect-file](https://www.npmjs.com/package/detect-file) which will attempt to detect the given filepath by using [fs-exists-sync](https://www.npmjs.com/package/fs-exists-sync) first. If the file is not detected and the `nocase` option is true, all the files in the filepath's directory will be checked in an attempt to detect the correct file and return the filepath with the correct case.

The changes also return the filepath from `detect-file` to ensure the correct case is used when `nocase` is true.

Included new test fixture and tests for case sensitive file systems.
Updated `.travis.yml` to include both linux and osx.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@doowb thanks for pulling all of this together.

**Comment by tkellen** [comment]
just chiming in to say that you're welcome to cut releases on this module as you see fit @jonschlinkert!

**Comment by tkellen** [comment]
also, thanks for digging into this @doowb!

**Comment by jonschlinkert** [comment]
> just chiming in to say that you're welcome to cut releases on this module as you see fit

thank @tkellen! 

@phated if you're good with this, I'll get it merged and published

**Comment by phated** [comment]
Sorry, I didn't see this come through. After a quick review on my phone, it looks great!

**Comment by jonschlinkert** [comment]
k I'll get this merged today. thx!

**Comment by jonschlinkert** [comment]
ok, I overestimated my day. tomorrow should be a little less busy, I'll get this merged in ASAP

**Pull request merged**
